config/routes.rb
Rails.application.routes.draw do
  resources :room_messages
  resources :rooms
  devise_for :users
  
  root controller: :rooms, action: :index
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/room.rb
class Room < ApplicationRecord
    has_many :room_messages, dependent: :destroy, inverse_of: :room
end

app/models/room_message.rb
class RoomMessage < ApplicationRecord
  belongs_to :room, inverse_of: :room_messages
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  validates :username, uniqueness: true, presence: true
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :authenticate_user!

    before_action :configure_permitted_parameters, if: :devise_controller?

    protected

    def configure_permitted_parameters
        devise_parameter_sanitizer.permit(:sign_up, keys: [:email, :username])
    end
end

app/controllers/room_messages_controller.rb
class RoomMessagesController < ApplicationController
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
    def index
        @rooms = Room.all
    end

    def new
        @room = Room.new
    end

    def show
        @room_message = RoomMessage.new room: @room
        # @room_messages = @room.room_message.includes(:user)
    end

    def create
        @room = Room.new permitted_parameters

        if @room.save
            flash[:success] = "Room #{@room.name} was successfully created"
            redirect_to rooms_path
        else
            render :new
        end
    end

    def edit
    end

    def update
        if @room.update_attributes(permitted_parameters)
            flash[:success] = "Room #{@room.name} was successfully updated"
            redirect_to rooms_path
        else
            render :new
        end
    end

    protected

    def load_entities
        @rooms = Room.all
        @room = Room.find(params[:id]) if params[:id]
    end

    def permitted_parameters
        params.require(:room).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def gravatar_url(user)
        gravatar_id = Digest::MD5::hexdigest(user.email).downcase
        url = "https://gravatar.com/avatar/#{gravatar_id}.png"
      end
      
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/room_messages_helper.rb
module RoomMessagesHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/layouts/_alert.html.erb
<svg xmlns="http://www.w3.org/2000/svg" style="display: none;">
    <symbol id="check-circle-fill" fill="currentColor" viewBox="0 0 16 16">
        <path
            d="M16 8A8 8 0 1 1 0 8a8 8 0 0 1 16 0zm-3.97-3.03a.75.75 0 0 0-1.08.022L7.477 9.417 5.384 7.323a.75.75 0 0 0-1.06 1.06L6.97 11.03a.75.75 0 0 0 1.079-.02l3.992-4.99a.75.75 0 0 0-.01-1.05z" />
    </symbol>
    <symbol id="info-fill" fill="currentColor" viewBox="0 0 16 16">
        <path
            d="M8 16A8 8 0 1 0 8 0a8 8 0 0 0 0 16zm.93-9.412-1 4.705c-.07.34.029.533.304.533.194 0 .487-.07.686-.246l-.088.416c-.287.346-.92.598-1.465.598-.703 0-1.002-.422-.808-1.319l.738-3.468c.064-.293.006-.399-.287-.47l-.451-.081.082-.381 2.29-.287zM8 5.5a1 1 0 1 1 0-2 1 1 0 0 1 0 2z" />
    </symbol>
    <symbol id="exclamation-triangle-fill" fill="currentColor" viewBox="0 0 16 16">
        <path
            d="M8.982 1.566a1.13 1.13 0 0 0-1.96 0L.165 13.233c-.457.778.091 1.767.98 1.767h13.713c.889 0 1.438-.99.98-1.767L8.982 1.566zM8 5c.535 0 .954.462.9.995l-.35 3.507a.552.552 0 0 1-1.1 0L7.1 5.995A.905.905 0 0 1 8 5zm.002 6a1 1 0 1 1 0 2 1 1 0 0 1 0-2z" />
    </symbol>
</svg>

<div class="alert alert-primary d-flex align-items-center" role="alert">
    <svg class="bi flex-shrink-0 me-2" width="24" height="24" role="img" aria-label="Info:">
        <use xlink:href="#info-fill" />
    </svg>
    <div>
        <%= notice %>
    </div>
</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark justify-content-between">
  <%= link_to 'CH-G', root_path, class:"navbar-brand" %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#nav-bar-collapse" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <% if current_user %>
    <div class="dropdown">
      <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        <img class="avatar" src="<%= gravatar_url(current_user) %>"> -->
        <%= current_user.username%>
      </a>

      <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
        <%= button_to 'Logout', destroy_user_session_path, method: :delete, class: 'dropdown-item' %>
      </div>
    </div>
  <% end %>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CH-G</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">
    <!-- <meta name="viewport" content="width=device-width,initial-scale=1"> -->
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application",media: "all"%>
    <%= javascript_include_tag 'application'%>
    <!-- <%= javascript_importmap_tags %> -->
  </head>
  <body>
    <div>
      <!-- <% if notice %>
        <%= render 'layouts/alert' %>
      <% end %> 
      <br>-->
      <div class="row">
        <div class="col-12">
          <%= render 'layouts/navbar' %>
          <div class="my-3 container">
            <%= yield %>
          </div>
        </div>
      </div>
    </div>
      <!-- <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2" crossorigin="anonymous"></script> -->
  </body>
</html>

app/views/rooms/_form.html.erb
<%= simple_form_for @room do |form| %>
  <%= form.input :name%>
  <br>
  <%= form.submit "Save", class: 'btn btn-success' %>
<% end %>

app/views/rooms/_rooms.html.erb
<div class="mb-3">
    <%= link_to "Create a room", new_room_path, class: "btn btn-primary" %>
  </div>

  <% if @rooms.present? %>
    <nav class="nav flex-column">
      <% @rooms.each do |room| %>
        <%= link_to room.name, room_path(room), class: "nav-link room-nav-link" %>
      <% end %>
    </nav>
  <% else %>
    <div class="text-muted">
      The are no rooms
    </div>
  <% end %>

app/views/rooms/edit.html.erb
<h1>
    Editing room <%= @room.name %>
</h1>
  
<%= render partial: 'form' %>
  

app/views/rooms/index.html.erb
<div class="row">
    <div class="col-12 col-md-3">
      <%= render 'rooms' %>      
    </div>
    <div class="col">
      <div class="alert alert-primary">
        <h4 class="alert-heading">
          Welcome to the RailsChatTutorial!
        </h4>
  
        <p>
          We need to talk.
        </p>
  
        <hr />
  
        <p>
          You can create or join a room from the sidebar.
        </p>
      </div>
    </div>
</div>

app/views/rooms/new.html.erb
<h1>
    Creating a room  
</h1>
  
<%= render partial: 'form' %>
  

app/views/rooms/show.html.erb
<h1>
    Room Name
  </h1>
  
  <div class="row">
    <div class="col-12 col-md-3">
      <%= render 'rooms' %>
    </div>
  
    <div class="col">
      <div class="chat">
        Msgs
      </div>
  
      <%= simple_form_for @room_message, remote: true do |form| %>
        <div class="input-group mb-3">
          <%= form.input :message, as: :string,
                                   wrapper: false,
                                   label: false,
                                   input_html: {
                                     class: 'chat-input'
                                   } %>
          <div class="input-group-append">
            <%= form.submit "Send", class: 'btn btn-primary chat-input' %>
          </div>
        </div>
  
        <%= form.input :room_id, as: :hidden %>
      <% end %>
    </div>
  </div>
  